# Generated by Django 5.1.4 on 2024-12-31 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_app.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comic')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='read_comics',
            field=models.ManyToManyField(related_name='readers', through='setup_app.UserComic', to='setup_app.comic'),
        ),
    ]
