# Generated by Django 5.1.4 on 2025-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0002_usercomic_user_read_comics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended_comics',
            field=models.ManyToManyField(blank=True, related_name='recommended_to_users', to='setup_app.comic'),
        ),
    ]
